/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/custom.glb --types --transform --keepmeshes --keepgroups --keepnames 
Files: public/models/custom.glb [175.74MB] > C:\Users\Gus\repos\r3f_ecommerce\custom-transformed.glb [3.32MB] (98%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Insole_Right']: THREE.Mesh
    ['Insole_Left']: THREE.Mesh
    ['Lining_Right']: THREE.Mesh
    ['Outsole_Back_Right']: THREE.Mesh
    ['Outsole_Back_Left']: THREE.Mesh
    ['Outsole_Bottom_Right']: THREE.Mesh
    ['outsole-bottom-l']: THREE.Mesh
    ['Outsole_Front_Right']: THREE.Mesh
    ['Outsole_Front_Left']: THREE.Mesh
    ['Outsole_Side_Right']: THREE.Mesh
    ['Outsole_Side_Left']: THREE.Mesh
    ['Seam_Line_Right']: THREE.Mesh
    ['Seam_Line_Left']: THREE.Mesh
    Back_Label_Right: THREE.Mesh
    Back_Label_Left: THREE.Mesh
    Foxing__Lining_Back_Right: THREE.Mesh
    Foxing__Lining_Back_Left: THREE.Mesh
    Foxing__Lining_Right: THREE.Mesh
    Foxing__Lining_Left: THREE.Mesh
    Lace__Dubrae_Right: THREE.Mesh
    Lace__Dubrae_Left: THREE.Mesh
    Midsole_Right: THREE.Mesh
    Midsole_Left: THREE.Mesh
    Plane006: THREE.Mesh
    Plane045: THREE.Mesh
    Plane007: THREE.Mesh
    Tip_Left_Right_: THREE.Mesh
    Tip_Right_Left_: THREE.Mesh
    Tip_Right: THREE.Mesh
    Tip_Left: THREE.Mesh
    Tip_Right_Right_: THREE.Mesh
    Tip_Left_Left_: THREE.Mesh
    Tongue_Right: THREE.Mesh
    Tongue_Left: THREE.Mesh
    Vamp_Right: THREE.Mesh
    Vamp_Left: THREE.Mesh
    ['Lining_Left']: THREE.Mesh
    Plane046: THREE.Mesh
  }
  materials: {
    ['govde.002']: THREE.MeshStandardMaterial
    ['bacık.002']: THREE.MeshStandardMaterial
    ['bacik.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/custom-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Insole_Right" geometry={nodes['Insole_Right'].geometry} material={materials['govde.002']} position={[-0.104, 0.026, -0.164]} rotation={[-Math.PI, -0.735, -Math.PI]} scale={0.254} />
        <mesh name="Insole_Left" geometry={nodes['Insole_Left'].geometry} material={materials['govde.002']} position={[0.175, 0.026, 0.144]} rotation={[0, 0.735, 0]} scale={[-0.254, 0.254, 0.254]} />
        <mesh name="Lining_Right" geometry={nodes['Lining_Right'].geometry} material={materials['govde.002']} position={[0.007, 0.189, -0.245]} rotation={[-Math.PI, -0.735, -Math.PI]} scale={0.254} />
        <mesh name="Outsole_Back_Right" geometry={nodes['Outsole_Back_Right'].geometry} material={materials['bacık.002']} position={[-0.068, 0.029, -0.162]} rotation={[-Math.PI, -0.735, -Math.PI]} scale={0.254} />
        <mesh name="Outsole_Back_Left" geometry={nodes['Outsole_Back_Left'].geometry} material={materials['bacık.002']} position={[0.177, 0.029, 0.109]} rotation={[0, 0.735, 0]} scale={[-0.254, 0.254, 0.254]} />
        <mesh name="Outsole_Bottom_Right" geometry={nodes['Outsole_Bottom_Right'].geometry} material={materials['bacık.002']} position={[-0.104, 0.013, -0.164]} rotation={[-Math.PI, -0.735, -Math.PI]} scale={0.254} />
        <mesh name="outsole-bottom-l" geometry={nodes['outsole-bottom-l'].geometry} material={materials['bacık.002']} position={[0.175, 0.013, 0.144]} rotation={[0, 0.735, 0]} scale={[-0.254, 0.254, 0.254]} />
        <mesh name="Outsole_Front_Right" geometry={nodes['Outsole_Front_Right'].geometry} material={materials['bacık.002']} position={[-0.459, 0.03, 0.173]} rotation={[-Math.PI, -0.735, -Math.PI]} scale={0.254} />
        <mesh name="Outsole_Front_Left" geometry={nodes['Outsole_Front_Left'].geometry} material={materials['bacık.002']} position={[-0.197, 0.03, 0.464]} rotation={[0, 0.735, 0]} scale={[-0.254, 0.254, 0.254]} />
        <mesh name="Outsole_Side_Right" geometry={nodes['Outsole_Side_Right'].geometry} material={materials['bacık.002']} position={[-0.069, 0.011, -0.206]} rotation={[-Math.PI, -0.735, -Math.PI]} scale={0.254} />
        <mesh name="Outsole_Side_Left" geometry={nodes['Outsole_Side_Left'].geometry} material={materials['bacık.002']} position={[0.22, 0.011, 0.114]} rotation={[0, 0.735, 0]} scale={[-0.254, 0.254, 0.254]} />
        <mesh name="Seam_Line_Right" geometry={nodes['Seam_Line_Right'].geometry} material={materials['bacık.002']} position={[-0.138, 0.087, -0.145]} rotation={[-Math.PI, -0.735, -Math.PI]} scale={0.254} />
        <mesh name="Seam_Line_Left" geometry={nodes['Seam_Line_Left'].geometry} material={materials['bacık.002']} position={[0.152, 0.087, 0.176]} rotation={[0, 0.735, 0]} scale={[-0.254, 0.254, 0.254]} />
        <mesh name="Back_Label_Right" geometry={nodes.Back_Label_Right.geometry} material={materials['govde.002']} position={[0.243, 0.342, -0.434]} rotation={[-Math.PI, -0.735, -Math.PI]} scale={0.254} />
        <mesh name="Back_Label_Left" geometry={nodes.Back_Label_Left.geometry} material={materials['govde.002']} position={[0.478, 0.342, -0.173]} rotation={[0, 0.735, 0]} scale={[-0.254, 0.254, 0.254]} />
        <mesh name="Foxing__Lining_Back_Right" geometry={nodes.Foxing__Lining_Back_Right.geometry} material={materials['govde.002']} position={[0.109, 0.214, -0.336]} rotation={[-Math.PI, -0.735, -Math.PI]} scale={0.254} />
        <mesh name="Foxing__Lining_Back_Left" geometry={nodes.Foxing__Lining_Back_Left.geometry} material={materials['govde.002']} position={[0.367, 0.214, -0.05]} rotation={[0, 0.735, 0]} scale={[-0.254, 0.254, 0.254]} />
        <mesh name="Foxing__Lining_Right" geometry={nodes.Foxing__Lining_Right.geometry} material={materials['govde.002']} position={[0.007, 0.198, -0.245]} rotation={[-Math.PI, -0.735, -Math.PI]} scale={0.254} />
        <mesh name="Foxing__Lining_Left" geometry={nodes.Foxing__Lining_Left.geometry} material={materials['govde.002']} position={[0.266, 0.198, 0.042]} rotation={[0, 0.735, 0]} scale={[-0.254, 0.254, 0.254]} />
        <mesh name="Lace__Dubrae_Right" geometry={nodes.Lace__Dubrae_Right.geometry} material={materials['bacik.002']} position={[-0.309, 0.288, -0.008]} rotation={[Math.PI / 2, 0, 0.836]} scale={0.025} />
        <mesh name="Lace__Dubrae_Left" geometry={nodes.Lace__Dubrae_Left.geometry} material={materials['bacik.002']} position={[-0.001, 0.288, 0.333]} rotation={[Math.PI / 2, 0, 0.836]} scale={[-0.025, 0.025, 0.025]} />
        <mesh name="Midsole_Right" geometry={nodes.Midsole_Right.geometry} material={materials['bacık.002']} position={[-0.138, 0.084, -0.145]} rotation={[-Math.PI, -0.735, -Math.PI]} scale={0.254} />
        <mesh name="Midsole_Left" geometry={nodes.Midsole_Left.geometry} material={materials['bacık.002']} position={[0.152, 0.084, 0.176]} rotation={[0, 0.735, 0]} scale={[-0.254, 0.254, 0.254]} />
        <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials['bacik.002']} position={[-0.235, 0.302, -0.206]} rotation={[-2.483, -0.86, -2.622]} scale={[0.262, 0.257, 0.277]} />
        <mesh name="Plane045" geometry={nodes.Plane045.geometry} material={materials['bacik.002']} position={[0.203, 0.302, 0.279]} rotation={[-0.439, 0.415, 0.18]} scale={[-0.262, 0.257, 0.277]} />
        <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['bacik.002']} position={[-0.102, 0.302, -0.058]} rotation={[-0.411, 0.292, 0.122]} scale={[-0.276, 0.259, 0.304]} />
        <mesh name="Tip_Left_Right_" geometry={nodes.Tip_Left_Right_.geometry} material={materials['govde.002']} position={[-0.135, 0.185, 0.027]} rotation={[0, 0.858, 0]} scale={[-0.256, 0.254, 0.259]} />
        <mesh name="Tip_Right_Left_" geometry={nodes.Tip_Right_Left_.geometry} material={materials['govde.002']} position={[-0.018, 0.185, 0.156]} rotation={[-Math.PI, -0.603, -Math.PI]} scale={[0.256, 0.254, 0.259]} />
        <mesh name="Tip_Right" geometry={nodes.Tip_Right.geometry} material={materials['govde.002']} position={[-0.357, 0.16, 0.037]} rotation={[-Math.PI, -0.735, -Math.PI]} scale={0.254} />
        <mesh name="Tip_Left" geometry={nodes.Tip_Left.geometry} material={materials['govde.002']} position={[-0.05, 0.16, 0.376]} rotation={[0, 0.735, 0]} scale={[-0.254, 0.254, 0.254]} />
        <mesh name="Tip_Right_Right_" geometry={nodes.Tip_Right_Right_.geometry} material={materials['govde.002']} position={[-0.329, 0.185, -0.188]} rotation={[-Math.PI, -0.735, -Math.PI]} scale={0.254} />
        <mesh name="Tip_Left_Left_" geometry={nodes.Tip_Left_Left_.geometry} material={materials['govde.002']} position={[0.176, 0.185, 0.371]} rotation={[0, 0.735, 0]} scale={[-0.254, 0.254, 0.254]} />
        <mesh name="Tongue_Right" geometry={nodes.Tongue_Right.geometry} material={materials['bacik.002']} position={[-0.129, 0.315, -0.171]} rotation={[-Math.PI, -0.57, -Math.PI]} scale={[0.257, 0.254, 0.262]} />
        <mesh name="Tongue_Left" geometry={nodes.Tongue_Left.geometry} material={materials['bacik.002']} position={[0.179, 0.315, 0.17]} rotation={[0, 0.886, 0]} scale={[-0.257, 0.254, 0.262]} />
        <mesh name="Vamp_Right" geometry={nodes.Vamp_Right.geometry} material={materials['govde.002']} position={[-0.187, -0.015, -0.178]} rotation={[-Math.PI, -0.735, -Math.PI]} scale={0.254} />
        <mesh name="Vamp_Left" geometry={nodes.Vamp_Left.geometry} material={materials['govde.002']} position={[0.18, -0.015, 0.228]} rotation={[0, 0.735, 0]} scale={[-0.254, 0.254, 0.254]} />
        <mesh name="Lining_Left" geometry={nodes['Lining_Left'].geometry} material={materials['govde.002']} position={[0.266, 0.189, 0.042]} rotation={[0, 0.735, 0]} scale={[-0.254, 0.254, 0.254]} />
        <mesh name="Plane046" geometry={nodes.Plane046.geometry} material={materials['bacik.002']} position={[0.07, 0.302, 0.132]} rotation={[-2.105, -0.917, -2.191]} scale={[0.276, 0.259, 0.304]} />
      </group>
    </group>
  )
}

useGLTF.preload('/custom-transformed.glb')
